version: "3.8"

services:
    codebot:
        image: serbanblebea/codebot
        build: ./
        container_name: codebot
        ports:
            - "3000:3000"
    mongodb:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27015:27017"
        volumes:
            - ./mongodb-volume:/data/db