version: "3.8"

services:
    codebot:
        image: serbanblebea/codebot:v0.1
        build: ./
        container_name: codebot
        ports:
            - "8080:8080"
        environment:
            SLACK_TOKEN: ${SLACK_TOKEN}
            WITAI_TOKEN: ${WITAI_TOKEN}
            HTTP_PORT: ${HTTP_PORT} 
    mongodb:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27015:27017"
        volumes:
            - ./mongodb-volume:/data/db