version: "3.8"

services:
    codebot:
        image: serbanblebea/codebot:v0.1
        build: ./
        container_name: codebot
        ports:
            - "8080:8080"
        environment:
            SLACK_TOKEN: ${SLACK_TOKEN}
            WITAI_TOKEN: ${WITAI_TOKEN}
            HTTP_PORT: ${HTTP_PORT} 
    database:
        image: mariadb:latest
        container_name: database
        volumes:
            - ./volume/database:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=pass
            - MYSQL_USER=admin
            - MYSQL_DATABASE=codebot